//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos_Museo_PPAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CambiosEstados
    {
        public Nullable<System.DateTime> fechaFin { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.TimeSpan> horaFin { get; set; }
        public Nullable<System.TimeSpan> horaInicio { get; set; }
        public Nullable<int> numeroReserva { get; set; }
        public Nullable<int> estado { get; set; }
        public int id { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual ReservasVisitas ReservasVisitas { get; set; }
    }
}
