//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos_Museo_PPAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesExposiciones
    {
        public Nullable<int> obra { get; set; }
        public Nullable<int> idExp { get; set; }
        public Nullable<int> lugarAsignado { get; set; }
        public int id { get; set; }
    
        public virtual Exposiciones Exposiciones { get; set; }
        public virtual Obras Obras { get; set; }
    }
}
