//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos_Museo_PPAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exposiciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exposiciones()
        {
            this.PublicosDestino = new HashSet<PublicosDestino>();
            this.DetallesExposiciones = new HashSet<DetallesExposiciones>();
            this.ReservasVisitas = new HashSet<ReservasVisitas>();
        }
    
        public Nullable<int> sede { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public Nullable<System.DateTime> fechaFinReplanificada { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }

        public Nullable<System.DateTime> fechaInicioReplanificada { get; set; }
        public string nombre { get; set; }
        public Nullable<int> tipoExp { get; set; }
        public Nullable<System.TimeSpan> horaApertura { get; set; }
        public Nullable<System.TimeSpan> horaCierre { get; set; }
        public int id { get; set; }
    
        public virtual Sedes Sedes { get; set; }
        public virtual TipoExposiciones TipoExposiciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PublicosDestino> PublicosDestino { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesExposiciones> DetallesExposiciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservasVisitas> ReservasVisitas { get; set; }
    }
}
