//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos_Museo_PPAI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DSI_PPAI_MuseoEntities1 : DbContext
    {
        public DSI_PPAI_MuseoEntities1()
            : base("name=DSI_PPAI_MuseoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Escuelas> Escuelas { get; set; }
        public virtual DbSet<Sedes> Sedes { get; set; }
        public virtual DbSet<TipoVisitas> TipoVisitas { get; set; }
        public virtual DbSet<Exposiciones> Exposiciones { get; set; }
        public virtual DbSet<PublicosDestino> PublicosDestino { get; set; }
        public virtual DbSet<TipoExposiciones> TipoExposiciones { get; set; }
        public virtual DbSet<AsignacionesVisitas> AsignacionesVisitas { get; set; }
        public virtual DbSet<CambiosEstados> CambiosEstados { get; set; }
        public virtual DbSet<Cargos> Cargos { get; set; }
        public virtual DbSet<DetallesExposiciones> DetallesExposiciones { get; set; }
        public virtual DbSet<DiasSemana> DiasSemana { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<HorariosEmpleados> HorariosEmpleados { get; set; }
        public virtual DbSet<Obras> Obras { get; set; }
        public virtual DbSet<ReservasVisitas> ReservasVisitas { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
