//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos_Museo_PPAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservasVisitas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReservasVisitas()
        {
            this.AsignacionesVisitas = new HashSet<AsignacionesVisitas>();
            this.CambiosEstados = new HashSet<CambiosEstados>();
            this.Exposiciones = new HashSet<Exposiciones>();
        }
    
        public Nullable<int> cantidadAlumnos { get; set; }
        public Nullable<int> cantidadAlumnosConfirmada { get; set; }
        public Nullable<int> sede { get; set; }
        public Nullable<double> duracionEstimada { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<int> escuela { get; set; }
        public Nullable<System.TimeSpan> horaCreacion { get; set; }
        public Nullable<System.TimeSpan> horaInicioReal { get; set; }
        public Nullable<System.TimeSpan> horaFinReal { get; set; }
        public int numeroReserva { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionesVisitas> AsignacionesVisitas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CambiosEstados> CambiosEstados { get; set; }
        public virtual Escuelas Escuelas { get; set; }
        public virtual Sedes Sedes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exposiciones> Exposiciones { get; set; }
    }
}
